;;;;;;;;;; General ;;;;;;;;;;

[Intro Skip]
; Skips company logos, autosave dialog and attract movie.
Enabled = true

[FOV]
; Adjust "Gameplay" or "Battle" multiplier values to increase/decrease FOV. i.e 1.2 = 20% higher FOV.
; Valid range - 0.2 to 2.0
Gameplay = 1.0
Battle = 1.0

;;;;;;;;;; Ultrawide/Narrower ;;;;;;;;;;

[Custom Resolution]
; Replaces 3840x2160 resolution option in-game.
; You can leave width and height at 0 if you want your desktop resolution used instead.
Enabled = true
Width = 0
Height = 0

[Fix HUD]
; Set to true to center the HUD to 16:9.
Enabled = true

;;;;;;;;;; Graphics ;;;;;;;;;;

[Disable Photo Mode Restriction]
; Set to true to stop character models becoming invisible in photo mode.
Enabled = true

[LOD Tweaks]
; Controls the draw distance of NPCs. Only applies when "Animation Distance" is set to the "Long" setting.
; "Long" = 1.0. Valid Range - 0.1 to 10
AnimationDistance = 1.0